Repository Charging-Life/BACK-END, pull requests merged in 2022-10, with the labels that each got.

#14 Feature/회원가입
  build.gradle
  src/main/java/com/example/charging_life/car/Car.java
  src/main/java/com/example/charging_life/car/CarService.java
  src/main/java/com/example/charging_life/car/JpaCarRepo.java
  src/main/java/com/example/charging_life/config/EmailConfig.java
  src/main/java/com/example/charging_life/email/Email.java
  src/main/java/com/example/charging_life/email/EmailController.java
  src/main/java/com/example/charging_life/email/EmailService.java
  src/main/java/com/example/charging_life/email/JpaEmailRepo.java
  src/main/java/com/example/charging_life/exception/ExceptionEnum.java
  src/main/java/com/example/charging_life/member/MemberController.java
  src/main/java/com/example/charging_life/member/dto/EmailDto.java
  src/main/java/com/example/charging_life/member/dto/MemberReqDto.java
  src/main/java/com/example/charging_life/member/dto/MemberResDto.java
  src/main/java/com/example/charging_life/member/entity/Member.java
Labels: 🔨 기능추가, ⚒ 기능 개선

#15 공공데이터 api 부분 완료
  src/main/java/com/example/charging_life/board/BoardController.java
  src/main/java/com/example/charging_life/board/BoardService.java
  src/main/java/com/example/charging_life/board/entity/Board.java
  src/main/java/com/example/charging_life/board/entity/Catagory.java
  src/main/java/com/example/charging_life/board/entity/File.java
  src/main/java/com/example/charging_life/board/repository/JpaBoardRepository.java
  src/main/java/com/example/charging_life/board/repository/JpaFileRepository.java
  src/main/java/com/example/charging_life/station/StationController.java
  src/main/java/com/example/charging_life/station/StationService.java
  src/main/java/com/example/charging_life/station/dto/BusinessResDto.java
  src/main/java/com/example/charging_life/station/dto/ChargerResDto.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
  src/main/java/com/example/charging_life/station/dto/StationAnalysisDto.java
  src/main/java/com/example/charging_life/station/entity/Charger.java
  src/main/java/com/example/charging_life/station/entity/ChargingStation.java
  src/main/java/com/example/charging_life/station/entity/StationAnalysis.java
  src/main/java/com/example/charging_life/station/repository/JpaChargerRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaStationAnalysisRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaStationRepository.java
Labels: 🔨 기능추가, ⚒ 기능 개선

#16 UPDATE city search function, UPDATE scheduling
  src/main/java/com/example/charging_life/station/StationController.java
  src/main/java/com/example/charging_life/station/StationService.java
  src/main/java/com/example/charging_life/station/dto/BusinessResDto.java
  src/main/java/com/example/charging_life/station/dto/ChargerResDto.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
  src/main/java/com/example/charging_life/station/entity/Charger.java
  src/main/java/com/example/charging_life/station/entity/Zcode.java
  src/main/java/com/example/charging_life/station/repository/JpaBusinessRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaChargerRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaStationAnalysisRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaStationRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaZcodeRepository.java
Labels: 🔨 기능추가

#17 Feature/충전소목적지등록
  src/main/java/com/example/charging_life/alarm/AlarmService.java
  src/main/java/com/example/charging_life/email/EmailService.java
  src/main/java/com/example/charging_life/member/MemberController.java
  src/main/java/com/example/charging_life/member/MemberService.java
  src/main/java/com/example/charging_life/member/entity/MemberDestination.java
  src/main/java/com/example/charging_life/member/repo/JpaMemberDestinationRepo.java
  src/main/java/com/example/charging_life/member/repo/JpaMemberRepo.java
  src/main/java/com/example/charging_life/member/repo/JpaMemberStationRepo.java
  src/main/java/com/example/charging_life/station/StationController.java
  src/main/java/com/example/charging_life/station/StationService.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
Labels: 🔨 기능추가

#19 UPDATE dto
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
Labels: 🔨 기능추가

#18 Feature/충전소즐겨찾기여부
  src/main/java/com/example/charging_life/board/BoardController.java
  src/main/java/com/example/charging_life/board/BoardService.java
  src/main/java/com/example/charging_life/board/entity/Board.java
  src/main/java/com/example/charging_life/board/entity/Catagory.java
  src/main/java/com/example/charging_life/board/entity/File.java
  src/main/java/com/example/charging_life/board/repository/JpaBoardRepository.java
  src/main/java/com/example/charging_life/board/repository/JpaFileRepository.java
  src/main/java/com/example/charging_life/member/MemberController.java
  src/main/java/com/example/charging_life/member/MemberService.java
  src/main/java/com/example/charging_life/member/repo/JpaMemberStationRepo.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
Labels: 🔨 기능추가

#20 FIX 잘못된 어노테이션으로 인한 오류 수정
  src/main/java/com/example/charging_life/member/MemberController.java
Labels: 🔥 bug

#21 UPDATE find station by business function
  src/main/java/com/example/charging_life/station/StationController.java
  src/main/java/com/example/charging_life/station/StationService.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
  src/main/java/com/example/charging_life/station/repository/JpaBusinessRepository.java
  src/main/java/com/example/charging_life/station/repository/JpaStationRepository.java
Labels: 🔨 기능추가

#22 CREATE board, multipartFile List
  build.gradle
  src/main/java/com/example/charging_life/board/BoardController.java
  src/main/java/com/example/charging_life/board/BoardService.java
  src/main/java/com/example/charging_life/board/dto/BoardLikeReqDto.java
  src/main/java/com/example/charging_life/board/dto/BoardLikeResDto.java
  src/main/java/com/example/charging_life/board/dto/BoardListDto.java
  src/main/java/com/example/charging_life/board/dto/BoardReqDto.java
  src/main/java/com/example/charging_life/board/dto/BoardResDto.java
  src/main/java/com/example/charging_life/board/dto/BoardUpdateReqDto.java
  src/main/java/com/example/charging_life/board/dto/BoardUpdateResDto.java
  src/main/java/com/example/charging_life/board/entity/Board.java
  src/main/java/com/example/charging_life/board/entity/Category.java
  src/main/java/com/example/charging_life/board/entity/LikeMembers.java
  src/main/java/com/example/charging_life/board/repository/JpaBoardRepository.java
  src/main/java/com/example/charging_life/board/repository/JpaLikeMembersRepository.java
  src/main/java/com/example/charging_life/file/FileController.java
  src/main/java/com/example/charging_life/file/FileHandler.java
  src/main/java/com/example/charging_life/file/FileService.java
  src/main/java/com/example/charging_life/file/dto/FileDto.java
  src/main/java/com/example/charging_life/file/dto/FileResDto.java
  src/main/java/com/example/charging_life/file/entity/File.java
  src/main/java/com/example/charging_life/file/repository/JpaFileRepository.java
  src/main/java/com/example/charging_life/member/entity/Member.java
  src/main/java/com/example/charging_life/station/dto/ChargingStationDto.java
  src/main/java/com/example/charging_life/station/entity/ChargingStation.java
  src/main/resources/application.yml
Labels: 🔨 기능추가

#23 Feature/공공api와충전소조회
  src/main/java/com/example/charging_life/api/ApiController.java
  src/main/java/com/example/charging_life/api/ApiService.java
  src/main/java/com/example/charging_life/api/JpaStationAnalysisRepository.java
  src/main/java/com/example/charging_life/api/StationAnalysis.java
  src/main/java/com/example/charging_life/api/StationAnalysisDto.java
  src/main/java/com/example/charging_life/board/BoardController.java
  src/main/java/com/example/charging_life/board/BoardService.java
  src/main/java/com/example/charging_life/board/dto/BoardReqDto.java
  src/main/java/com/example/charging_life/board/entity/Board.java
  src/main/java/com/example/charging_life/board/entity/LikeMembers.java
  src/main/java/com/example/charging_life/exception/ExceptionEnum.java
  src/main/java/com/example/charging_life/file/FileHandler.java
  src/main/java/com/example/charging_life/file/FileService.java
  src/main/java/com/example/charging_life/member/entity/Member.java
  src/main/java/com/example/charging_life/station/StationController.java
  src/main/java/com/example/charging_life/station/StationService.java
  src/main/resources/application.yml
Labels: 🔨 기능추가, ⚒ 기능 개선

#25 FEAT 사용자 즐겨찾기 취소 & 관리자 관할 충전소 삭제 기능 추가
  src/main/java/com/example/charging_life/exception/ExceptionEnum.java
  src/main/java/com/example/charging_life/member/MemberController.java
  src/main/java/com/example/charging_life/member/MemberService.java
  src/main/java/com/example/charging_life/member/repo/JpaMemberStationRepo.java
Labels: 🔨 기능추가

#28 FIX 알람 - 충전소 연관관계 알람 - 충전기 연관관계로 수정
  src/main/java/com/example/charging_life/alarm/Alarm.java
  src/main/java/com/example/charging_life/alarm/AlarmController.java
  src/main/java/com/example/charging_life/alarm/AlarmService.java
  src/main/java/com/example/charging_life/alarm/ChargerStatus.java
  src/main/java/com/example/charging_life/alarm/JpaAlarmRepository.java
  src/main/java/com/example/charging_life/alarm/Status.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmResDto.java
  src/main/java/com/example/charging_life/alarm/dto/EnrollAlarmReqDto.java
  src/main/java/com/example/charging_life/alarm/dto/StationStat.java
  src/main/java/com/example/charging_life/exception/ExceptionEnum.java
Labels: 🔥 bug

#26 CREATE QRCODE with member and chargerStatus
  build.gradle
  src/main/java/com/example/charging_life/alarm/AlarmController.java
  src/main/java/com/example/charging_life/alarm/AlarmService.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmResDto.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmUserReqDto.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmUserResDto.java
  src/main/java/com/example/charging_life/alarm/entity/Alarm.java
  src/main/java/com/example/charging_life/alarm/entity/AlarmUser.java
  src/main/java/com/example/charging_life/alarm/entity/ChargerStatus.java
  src/main/java/com/example/charging_life/alarm/repository/JpaAlarmRepository.java
  src/main/java/com/example/charging_life/alarm/repository/JpaAlarmUserRepository.java
Labels: 🔨 기능추가

#27 Feature/user alarm
  src/main/java/com/example/charging_life/alarm/AlarmService.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmUserReqDto.java
  src/main/java/com/example/charging_life/alarm/dto/AlarmUserResDto.java
  src/main/java/com/example/charging_life/alarm/entity/AlarmUser.java
  src/main/java/com/example/charging_life/alarm/entity/ChargerStatus.java
  src/main/java/com/example/charging_life/exception/ExceptionEnum.java
Labels: 🔨 기능추가

#32 FEAT 회원 탈퇴기능 추가
  src/main/java/com/example/charging_life/member/MemberController.java
  src/main/java/com/example/charging_life/member/MemberService.java
  src/main/java/com/example/charging_life/member/entity/Member.java
Labels: 🔨 기능추가
